### ISSUE TITLE
Support for the most recent Atmosphère release (1.1.1)

### ISSUE THREAD

**Issue by Goma1337** [PabloZaiden/deviceid-exosphere-builder#14]
Hello, is there any chance this tool could get updated to support the latest release of atmosphère?

Thank you!

**Comment by PabloZaiden** [comment]
There are better solutions for this kind of issues now. You can try: https://github.com/CaramelDunes/prodinfo_gen

I won't be updating this, but it's quite easy to do, updating the dockerfile versions
