### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Kronos2308** [PabloZaiden/deviceid-exosphere-builder#2]
after trying this method I must say that it works

but it can be simplified a bit

the id can be retrieved from the prodinfo at 548-555 hex

i just restore the prodinfo from the other console and spoof the id with a mod of exosphere

that was enough to make a brikachu console boot

a least your nand is corrupt in that case the bis keys must be use

**Comment by PabloZaiden** [comment]
That's for the case you only have a nuked prodinfo. If you have to recreate the nand from scratch, you'll probably need to do the whole thing. Of course it can be simplified, but as it is right now, it covers most cases in a generic way.
