### ISSUE TITLE
doesn't work on atmos 0.14.4

### ISSUE THREAD

**Issue by Heartbeat-Heartbreak** [PabloZaiden/deviceid-exosphere-builder#3]
I have a emunand for test, everything follows the README and it works fine in atmos 0.14.1.
I upgraded the emu firmware to 10.2.0, I changed from "atmos 0.14.1" + "exosphere.bin 0.14.1" to "atmos 0.14.4"+"exosphere.bin 0.14.4", then my emu can not boot. When I use the fusse primary.bin, it gives me a black screen after the "Sept" and "Atmosphere" logo, when I use the hekate-fusee secondary, it just only black screen and do not show anythings.
I tried change back to "atmos 0.14.1" + "exosphere.bin 0.14.1", everything works fine.
I tried change to "atmos 0.14.3"+"exosphere.bin 0.14.3" (I created it a few days ago but I never used it), everything works fine.

**Comment by costelabr17** [comment]
last build is damaged yet, i see today trying new build in docker today more latter, btw the source of pablo is updated you can use

**Comment by PabloZaiden** [comment]
I have it working with 0.14.4
Try the 0.14.4 docker tag
