### ISSUE TITLE
Error when trying to build exosphere file via MSys2

### ISSUE THREAD

**Issue by Wat6656** [PabloZaiden/deviceid-exosphere-builder#5]
error: return-statement with no value, in function returning 'u64' {aka 'long unsigned int'} [-fpermissive]

struggling to figure out where this is coming from. I am using MSys2 on windows 10 to build the file. the build works on docker, but I am trying to learn/understand how to use devkit and other applications. 

Thanks!

**Comment by PabloZaiden** [comment]
Windows is not supported in any fashion for building this. If it works, great. If not, still great. 
If you want to use Windows with this, try going with WSL2.

However, if you find out a (simple) way to fix this under those conditions, you can send a PR and I'll gladly review it.

**Comment by Wat6656** [comment]
i am running linux as a seperate OS using  ubuntu. i still get the same error.

**Comment by PabloZaiden** [comment]
Write down the exact steps you’re running and the output.

**Comment by Wat6656** [comment]
In the atmosphere/exosphere folder i run: 
DEVICEID=0x0022334455667788 sed -i "/u64 GetDeviceId() {/ s/$/ return $DEVICEID;/"../libraries/libexosphere/source/fuse/fuse_api.cpp (with my device id).  

Then i run: make -j$(nproc) exosphere.bin 

this is the output:
make[1]: Entering directory '/home/xxxx/Atmosphere/exosphere/program'
fuse_api.cpp
crypto_bignum.cpp
crypto_bignum_operations.cpp
crypto_xts_mode_impl.cpp
/home/xxxx/Atmosphere/libraries/libexosphere/source/fuse/fuse_api.cpp: In function 'u64 ams::fuse::GetDeviceId()':
/home/xxxx/Atmosphere/libraries/libexosphere/source/fuse/fuse_api.cpp:279:25: error: return-statement with no value, in function returning 'u64' {aka 'long unsigned int'} [-fpermissive]
  279 |     u64 GetDeviceId() { return ; return ; return ;
      |                         ^~~~~~
/home/xxxx/Atmosphere/libraries/libexosphere/source/fuse/fuse_api.cpp:279:34: error: return-statement with no value, in function returning 'u64' {aka 'long unsigned int'} [-fpermissive]
  279 |     u64 GetDeviceId() { return ; return ; return ;
      |                                  ^~~~~~
/home/xxxx/Atmosphere/libraries/libexosphere/source/fuse/fuse_api.cpp:279:43: error: return-statement with no value, in function returning 'u64' {aka 'long unsigned int'} [-fpermissive]
  279 |     u64 GetDeviceId() { return ; return ; return ;
      |                                           ^~~~~~
crypto_aes_ctr_encryptor_decryptor.cpp
make[4]: *** [/opt/devkitpro/devkitA64/base_rules:14: fuse_api.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [arm64.mk:98: lib_nintendo_nx_arm64/libexosphere.a] Error 2
make[2]: *** [Makefile:22: arm64-release] Error 2
make[1]: *** [Makefile:82: check_libexo_release] Error 2
make[1]: Leaving directory '/home/xxxx/Atmosphere/exosphere/program'
make: *** [Makefile:56: check_program_release] Error 2

**Comment by PabloZaiden** [comment]
You made me realize that I've changed the way it works on docker, but didn't update it on the readme to do it manually.ç
I'll fix it and then close the issue.

Thanks!

**Comment by Wat6656** [comment]
ok, ran all the commands as you noted, here is the output: basically the same issue. again i am running unbuntu on a separate OS, not VM. any thoughts? 
 make -j$(nproc) exosphere.bin
make[1]: Entering directory '/home/xxx/Atmosphere/exosphere/program'
pkg1_api.cpp
crypto_aes_impl_security_engine.cpp
log_api.cpp
clkrst_api.cpp
i2c_api.cpp
flow_api.cpp
pmc_api.cpp
wdt_api.cpp
se_oaep.cpp
se_hash.cpp
se_suspend.cpp
se_execute.cpp
se_management.cpp
se_aes.cpp
se_rng.cpp
se_rsa.cpp
util_api.cpp
charger_api.cpp
fuse_api.cpp
pmic_api.cpp
actmon_api.cpp
/home/xxx/Atmosphere/libraries/libexosphere/source/fuse/fuse_api.cpp: In function 'u64 ams::fuse::GetDeviceId()':
/home/xxx/Atmosphere/libraries/libexosphere/source/fuse/fuse_api.cpp:279:25: error: return-statement with no value, in function returning 'u64' {aka 'long unsigned int'} [-fpermissive]
  279 |     u64 GetDeviceId() { return ;
      |                         ^~~~~~
gic_api.cpp
make[4]: *** [/opt/devkitpro/devkitA64/base_rules:14: fuse_api.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [arm64.mk:98: lib_nintendo_nx_arm64/libexosphere.a] Error 2
make[2]: *** [Makefile:22: arm64-release] Error 2
make[1]: *** [Makefile:82: check_libexo_release] Error 2
make[1]: Leaving directory '/home/xxx/Atmosphere/exosphere/program'
make: *** [Makefile:56: check_program_release] Error 2

**Comment by PabloZaiden** [comment]
You’re missing in the copied commands the sed and git am

**Comment by Wat6656** [comment]
> You’re missing in the copied commands the sed and git am
> […](#)

No I am not that dumb, I ran those ahead of the make command, I just didn’t include it.

**Comment by Wat6656** [comment]
> > You’re missing in the copied commands the sed and git am
> > […](#)
> 
> No I am not that dumb, I ran those ahead of the make command, I just didn’t include it.

I ran them in the atmosphere folder

**Comment by Wat6656** [comment]
any idea what might be causing this? thanks!

**Comment by PabloZaiden** [comment]
When you run the `sed` command, does the `deviceid.patch` file end up with your device id? If not, check what could be failing with the replacement. You can check how this is being executed in the docker container in the `build-deviceid-exosphere.sh` file

**Comment by Wat6656** [comment]
yup, i think your command is incorrect, i adjusted and used: sed -i "s/###DEVICEID###/0x0011223344556677/g" deviceid.patch, this properly put the device id into the file. setting the variable first does not seem to work. cant believe i missed that! Thank you!

**Comment by PabloZaiden** [comment]
I’m gonna clarify it on the docs.
