### ISSUE TITLE
getting error when trying to build ‘‘deviceid_exosphere.bin’’

### ISSUE THREAD

**Issue by djhaloman** [PabloZaiden/deviceid-exosphere-builder#8]
pablozaiden/deviceid-exosphere-builder:latest
Applying: deviceid
rm: cannot remove ‘…/libraries/libexosphere/build_nintendo_nx_arm/fuse_api.’: No such file or directory
rm: cannot remove ‘…/libraries/libexosphere/build_nintendo_nx_arm64/fuse_api.’: No such file or directory
make[1]: Entering directory ‘/Atmosphere/exosphere/program’
fuse_api.cpp

**Comment by PabloZaiden** [comment]
Does it create the binary file at the end? if that's the case, just ignore the error.

**Comment by lsp199308** [comment]
Whether self-sustaining mariko

**Comment by lsp199308** [comment]
Does mariko support
